version: '3.7'

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - /data/library/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fCEomFgy249GFq
      ME_CONFIG_MONGODB_ADMINPASSWORD: fCEomFgy249GFq
      ME_CONFIG_MONGODB_URL: mongodb://fCEomFgy249GFq:fCEomFgy249GFq@localhost:27017/
    network_mode: "host"
    # depends_on:
    #   - mongo


  # library:
  #   image: setre14/library
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SPRING_PROFILES_ACTIVE: prod
  #     PORT: 8080
  #     MONGO_HOST: mongo
  #     MONGO_PORT: 27017
  #     USERNAME: user
  #     PASSWORD: password
  #     DATABASE: library
  #     UPLOAD_DIR: /library/upload
  #     EXTRACT_DIR: /library/extract
  #     BOOK_DIR: /library/book
  #   volumes:
  #     - /data/library/mongo:/data/db
  #   depends_on:
  #     - mongo