server:
  port: 8080

spring:
  data: 
    mongodb:
      host: localhost:27017
#      host: home-server:27017
      port: 27017
      authentication-database: admin
      username: fCEomFgy249GFq
      password: fCEomFgy249GFq
      database: library-dev

  # jpa:
  #   defer-datasource-initialization: true
  # sql:
  #   init.mode: always

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: /wsp/sandbox/library-dev/upload
  extract-dir: /wsp/sandbox/library-dev/extract
  book-dir: /wsp/sandbox/library-dev/books


# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,at.setre14.library


